version: '3'
services:
  db:
    build: ./00_db/
    image: neo4j:plugins
    restart: always
    environment: 
      - NEO4J_AUTH=neo4j/passw0rd
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_shell_enabled=true
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - ./03_test_data:/var/lib/neo4j/import
  api:
    build: ./01_api/
    image: tribemaster:api
    restart: always
    environment: 
      - NEO4J_URI=bolt://db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=passw0rd
    ports:
      - "3000:3000"
volumes:
  neo4j_data:
  neo4j_logs:
