version: '3'
services:
  neo4j:
    build: .
    image: neo4j:plugins
    restart: always
    environment: 
      - NEO4J_AUTH=neo4j/passw0rd
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
